"""Query-parameter types. Generated by scripts/generate_types.py."""

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict

__all__ = ['SearchFilters', 'SubscriptionFilters']


class SearchFilters(TypedDict, total=False):
    """Advanced search."""

    # Unified keyword, tried as an eu_id, then a company-name prefix, then a person name —...
    q: NotRequired[str]
    # Company name prefix, matched against the folded legal name with quotes and invisible...
    company_name: NotRequired[str]
    # Exact eu_id lookup (no prefix expansion).
    eu_id: NotRequired[str]
    # Maximum number of hits to return per page. Hard upper bound is 50.
    limit: NotRequired[int]
    # Opaque pagination cursor. Pass the `pagination.next_cursor` from a previous response...
    cursor: NotRequired[str]
    # Field to order results by. Defaults to keyword-match relevance when `q` is given, oth...
    sort: NotRequired[Literal['name', 'revenue', 'profit', 'total_assets', 'employee_count']]
    # Sort direction. Defaults to `desc`.
    sort_direction: NotRequired[Literal['asc', 'desc']]
    # Exact Registernummer, digits only (`12345` for HRB 12345). Register numbers repeat ac...
    register_number: NotRequired[int]
    # Register type. Single-valued.
    register_type: NotRequired[Literal['HRA', 'HRB', 'GnR', 'PR', 'VR', 'GsR']]
    # Registering court (Registergericht), by its canonical Handelsregister name. An `Amtsg...
    register_court: NotRequired[Literal['Aachen', 'Ahaus', 'Amberg', 'Ansbach', 'Arnsberg', 'Aschaffenburg', 'Augsburg', 'Aurich', 'Bad Hersfeld', 'Bad Homburg v.d.H.', 'Bad Kreuznach', 'Bad Oeynhausen', 'Bamberg', 'Bayreuth', 'Berlin (Charlottenburg)', 'Bielefeld', 'Bocholt', 'Bochum', 'Bonn', 'Borken', 'Braunschweig', 'Bremen', 'Bremerhaven', 'Chemnitz', 'Coburg', 'Coesfeld', 'Cottbus', 'Darmstadt', 'Deggendorf', 'Dortmund', 'Dresden', 'Duisburg', 'Dülmen', 'Düren', 'Düsseldorf', 'Eschwege', 'Essen', 'Flensburg', 'Frankfurt am Main', 'Frankfurt/Oder', 'Freiburg', 'Friedberg', 'Fritzlar', 'Fulda', 'Fürth', 'Gelsenkirchen', 'Gießen', 'Gronau', 'Göttingen', 'Gütersloh', 'Hagen', 'Hamburg', 'Hamm', 'Hanau', 'Hannover', 'Hildesheim', 'Hof', 'Homburg', 'Ingolstadt', 'Iserlohn', 'Jena', 'Kaiserslautern', 'Kassel', 'Kempten (Allgäu)', 'Kerpen', 'Kiel', 'Kleve', 'Koblenz', 'Korbach', 'Krefeld', 'Köln', 'Königstein', 'Landau', 'Landshut', 'Langenfeld', 'Lebach', 'Leipzig', 'Lemgo', 'Limburg', 'Ludwigshafen a.Rhein (Ludwigshafen)', 'Lübeck', 'Lüdinghausen', 'Lüneburg', 'Mainz', 'Mannheim', 'Marburg', 'Memmingen', 'Merzig', 'Montabaur', 'Mönchengladbach', 'München', 'Münster', 'Neubrandenburg', 'Neunkirchen', 'Neuruppin', 'Neuss', 'Nürnberg', 'Offenbach am Main', 'Oldenburg (Oldenburg)', 'Osnabrück', 'Ottweiler', 'Paderborn', 'Passau', 'Pinneberg', 'Potsdam', 'Recklinghausen', 'Regensburg', 'Rostock', 'Saarbrücken', 'Saarlouis', 'Schleiden', 'Schweinfurt', 'Schwerin', 'Siegburg', 'Siegen', 'St. Ingbert (St Ingbert)', 'St. Wendel (St Wendel)', 'Stadthagen', 'Steinfurt', 'Stendal', 'Stralsund', 'Straubing', 'Stuttgart', 'Tostedt', 'Traunstein', 'Ulm', 'Völklingen', 'Walsrode', 'Weiden i. d. OPf.', 'Wetzlar', 'Wiesbaden', 'Wittlich', 'Wuppertal', 'Würzburg', 'Zweibrücken']]
    # Registered seat city, matched exactly but umlaut-insensitively. Multi-valued, and OR-...
    city: NotRequired[list[str]]
    # German federal state. Multi-valued; also accepts postal codes (`BY`, `NRW`) and Engli...
    bundesland: NotRequired[list[Literal['Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen']]]
    # Earliest founding date (inclusive, `YYYY-MM-DD`).
    founded_from: NotRequired[str]
    # Latest founding date (inclusive, `YYYY-MM-DD`).
    founded_to: NotRequired[str]
    # Minimum latest reported revenue in EUR, inclusive. Most German companies file abridge...
    revenue_min: NotRequired[float]
    # Maximum latest reported revenue in EUR, inclusive.
    revenue_max: NotRequired[float]
    # Minimum latest reported profit in EUR, inclusive.
    profit_min: NotRequired[float]
    # Maximum latest reported profit in EUR, inclusive.
    profit_max: NotRequired[float]
    # Minimum balance-sheet total (Bilanzsumme) in EUR, inclusive. Every filing company pub...
    total_assets_min: NotRequired[float]
    # Maximum balance-sheet total (Bilanzsumme) in EUR, inclusive.
    total_assets_max: NotRequired[float]
    # Minimum reported employee count, inclusive. Reporting headcount is optional for most...
    employee_count_min: NotRequired[int]
    # Maximum reported employee count, inclusive.
    employee_count_max: NotRequired[int]
    # WZ 2025 industry code (German *Klassifikation der Wirtschaftszweige 2025*, compatible...
    wz_2025_code: NotRequired[list[str]]
    # High-level firmendata industry category. Expands server-side to WZ 2025 divisions. Mu...
    industry_slug: NotRequired[list[Literal['automotive', 'chemicals', 'construction', 'consulting', 'education', 'energy', 'financial_services', 'food', 'healthcare', 'holdings', 'hospitality', 'insurance', 'legal', 'logistics', 'manufacturing', 'media', 'mining', 'public_sector', 'technology', 'telecom', 'trade']]]
    # German legal form. Multi-valued. Common abbreviations and the long forms are accepted...
    rechtsform: NotRequired[list[Literal['GmbH', 'KG', 'e.K.', 'eGbR', 'UG', 'GmbH & Co. KG', 'OHG', 'PartG', 'e.V.', 'AG', 'eG', 'ausländische Rechtsform (HRB)', 'gGmbH', 'UG & Co. KG', 'ausländische Rechtsform', 'SE', 'sonstige juristische Person', 'EWIV', 'KGaA', 'Ltd. & Co. KG', 'sonstige juristische Person (HRA)', 'GmbH & Co. OHG', 'VVaG', 'SE & Co. KG', 'ausländische Rechtsform (HRA)', 'AG & Co. KG', 'ausländische Rechtsform (PR)', 'SCE', 'ausländische Rechtsform (GnR)', 'Stiftung & Co. KG', 'eG & Co. KG']]]
    # Name of an associated person — current or historical board member, shareholder or par...
    person_name: NotRequired[str]
    # CPV (Common Procurement Vocabulary) prefix from the EU tenders a company won — `45` m...
    cpv_code: NotRequired[str]
    # Minimum average birth year across the company's associated persons.
    avg_birth_year_min: NotRequired[int]
    # Maximum average birth year across the company's associated persons.
    avg_birth_year_max: NotRequired[int]
    # Company lifecycle status, resolved from the merged Handelsregister (SI + CD) and Inso...
    legal_status: NotRequired[list[Literal['active', 'in_liquidation', 'insolvent', 'dissolved', 'deleted']]]
    # Companies listed in at least one of these external registries. Multi-valued. - `Steue...
    membership: NotRequired[list[Literal['Steuerberaterkammer', 'Wirtschaftsprueferkammer', 'bbh', 'BaFin', 'LEI']]]
    # Exact LEI (ISO 17442), matched against the company's active LEI record. Case-insensit...
    lei_code: NotRequired[str]
    # Exact USt-IdNr (German / EU VAT number) as published on the company's Impressum. Case...
    ust_idnr: NotRequired[str]
    # Restrict to companies with (`true`) or without (`false`) a known website.
    has_website: NotRequired[bool]
    # Restrict to companies with (`true`) or without (`false`) a known email.
    has_email: NotRequired[bool]
    # Also search the German registers live for `q` / `company_name` (one is required with...
    fetch_realtime: NotRequired[bool]
    # Companies appearing in EU public-procurement notices (TED), in the selected role. Mul...
    tender_role: NotRequired[list[Literal['winner', 'buyer']]]

class SubscriptionFilters(TypedDict, total=False):
    """List subscriptions."""

    # Filter to subscriptions for one company.
    eu_id: NotRequired[str]
    # Filter by subscription type.
    subscription_type: NotRequired[Literal['details', 'history', 'shareholders', 'ubo', 'doc_articles_of_association', 'doc_company_registration', 'doc_model_protocol', 'doc_shareholder_list']]
    # Filter by `recurring` or `one_time`.
    mode: NotRequired[Literal['recurring', 'one_time']]
    limit: NotRequired[int]
    offset: NotRequired[int]
