"""Query-parameter types. Generated by scripts/generate_types.py."""

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict

__all__ = ['SearchFilters', 'SubscriptionFilters']


class SearchFilters(TypedDict, total=False):
    """Advanced search."""

    # Unified keyword. Tried in three phases, falling through when a phase returns zero hit...
    q: NotRequired[str]
    # Company name fragment. Prefix-matched against the folded legal name with quote / invi...
    company_name: NotRequired[str]
    # Exact eu_id lookup (no prefix expansion).
    eu_id: NotRequired[str]
    # Maximum number of hits to return per page. Hard upper bound is 50.
    limit: NotRequired[int]
    # Opaque pagination cursor. Pass the `pagination.next_cursor` from a previous response...
    cursor: NotRequired[str]
    # Field to sort by. Defaults to keyword-match relevance when `q` is provided; otherwise...
    sort: NotRequired[Literal['name', 'city', 'bundesland', 'industry', 'revenue', 'profit', 'employee_count', 'cpv']]
    # Sort direction. Defaults to `desc`.
    sort_direction: NotRequired[Literal['asc', 'desc']]
    # Filter by exact register number / Registernummer (e.g. `12345` for HRB 12345). Digits...
    register_number: NotRequired[int]
    # Filter by register type.
    register_type: NotRequired[Literal['HRA', 'HRB', 'GnR', 'PR', 'VR', 'GsR']]
    # Filter by registering court (Registergericht). Enum values are the canonical court na...
    register_court: NotRequired[Literal['Aachen', 'Ahaus', 'Amberg', 'Ansbach', 'Arnsberg', 'Aschaffenburg', 'Augsburg', 'Aurich', 'Bad Hersfeld', 'Bad Homburg v.d.H.', 'Bad Kreuznach', 'Bad Oeynhausen', 'Bamberg', 'Bayreuth', 'Berlin (Charlottenburg)', 'Bielefeld', 'Bocholt', 'Bochum', 'Bonn', 'Borken', 'Braunschweig', 'Bremen', 'Bremerhaven', 'Chemnitz', 'Coburg', 'Coesfeld', 'Cottbus', 'Darmstadt', 'Deggendorf', 'Dortmund', 'Dresden', 'Duisburg', 'Dülmen', 'Düren', 'Düsseldorf', 'Eschwege', 'Essen', 'Flensburg', 'Frankfurt am Main', 'Frankfurt/Oder', 'Freiburg', 'Friedberg', 'Fritzlar', 'Fulda', 'Fürth', 'Gelsenkirchen', 'Gießen', 'Gronau', 'Göttingen', 'Gütersloh', 'Hagen', 'Hamburg', 'Hamm', 'Hanau', 'Hannover', 'Hildesheim', 'Hof', 'Homburg', 'Ingolstadt', 'Iserlohn', 'Jena', 'Kaiserslautern', 'Kassel', 'Kempten (Allgäu)', 'Kerpen', 'Kiel', 'Kleve', 'Koblenz', 'Korbach', 'Krefeld', 'Köln', 'Königstein', 'Landau', 'Landshut', 'Langenfeld', 'Lebach', 'Leipzig', 'Lemgo', 'Limburg', 'Ludwigshafen a.Rhein (Ludwigshafen)', 'Lübeck', 'Lüdinghausen', 'Lüneburg', 'Mainz', 'Mannheim', 'Marburg', 'Memmingen', 'Merzig', 'Montabaur', 'Mönchengladbach', 'München', 'Münster', 'Neubrandenburg', 'Neunkirchen', 'Neuruppin', 'Neuss', 'Nürnberg', 'Offenbach am Main', 'Oldenburg (Oldenburg)', 'Osnabrück', 'Ottweiler', 'Paderborn', 'Passau', 'Pinneberg', 'Potsdam', 'Recklinghausen', 'Regensburg', 'Rostock', 'Saarbrücken', 'Saarlouis', 'Schleiden', 'Schweinfurt', 'Schwerin', 'Siegburg', 'Siegen', 'St. Ingbert (St Ingbert)', 'St. Wendel (St Wendel)', 'Stadthagen', 'Steinfurt', 'Stendal', 'Stralsund', 'Straubing', 'Stuttgart', 'Tostedt', 'Traunstein', 'Ulm', 'Völklingen', 'Walsrode', 'Weiden i. d. OPf.', 'Wetzlar', 'Wiesbaden', 'Wittlich', 'Wuppertal', 'Würzburg', 'Zweibrücken']]
    # Filter by registered seat city (exact match, umlaut-insensitive via `de_fold`). Repea...
    city: NotRequired[list[str]]
    # Filter by one or more German federal states. Repeat the parameter for multiple values...
    bundesland: NotRequired[list[Literal['Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen']]]
    # Earliest founding date (inclusive, `YYYY-MM-DD`).
    founded_from: NotRequired[str]
    # Latest founding date (inclusive, `YYYY-MM-DD`).
    founded_to: NotRequired[str]
    # Minimum latest reported revenue in EUR (inclusive). Companies with no revenue on file...
    revenue_min: NotRequired[float]
    # Maximum latest reported revenue in EUR (inclusive). Companies with no revenue on file...
    revenue_max: NotRequired[float]
    # Minimum latest reported profit in EUR (inclusive). Companies with no profit on file n...
    profit_min: NotRequired[float]
    # Maximum latest reported profit in EUR (inclusive). Companies with no profit on file n...
    profit_max: NotRequired[float]
    # Minimum balance-sheet total (Bilanzsumme) in EUR, inclusive. Present for ~35% of the...
    total_assets_min: NotRequired[float]
    # Maximum balance-sheet total (Bilanzsumme) in EUR, inclusive.
    total_assets_max: NotRequired[float]
    # Minimum reported employee count (inclusive).
    employee_count_min: NotRequired[int]
    # Maximum reported employee count (inclusive).
    employee_count_max: NotRequired[int]
    # One or more WZ 2025 codes (German *Klassifikation der Wirtschaftszweige 2025*, compat...
    wz_2025_code: NotRequired[list[str]]
    # One or more firmendata industry slugs. Each expands to a list of 2-digit WZ 2025 divi...
    industry_slug: NotRequired[list[Literal['automotive', 'chemicals', 'construction', 'consulting', 'education', 'energy', 'financial_services', 'food', 'healthcare', 'holdings', 'hospitality', 'insurance', 'legal', 'logistics', 'manufacturing', 'media', 'mining', 'public_sector', 'technology', 'telecom', 'trade']]]
    # One or more German legal-form short names (e.g. `GmbH`, `AG`, `GmbH & Co. KG`). Serve...
    rechtsform: NotRequired[list[Literal['GmbH', 'KG', 'e.K.; e.Kfm.; e.Kfr.', 'eGbR', 'UG', 'GmbH & Co. KG', 'OHG', 'PartG', 'AG', 'eG', 'ausl. Rechtsform', 'Rechtsform ausländischen Rechts HRB', 'e.V.', 'gGmbH', 'UG & Co. KG', 'SE', 'EWIV', 'KGaA', 'sonst. juristische Person, d. im HRA eingetragen ist', 'VVaG', 'SCE']]]
    # Filter by associated person's name (current or historical board member, shareholder,...
    person_name: NotRequired[str]
    # Filter by Common Procurement Vocabulary (CPV) code from public-procurement awards.
    cpv_code: NotRequired[str]
    # Minimum average birth year across a company's associated persons (board, shareholders...
    avg_birth_year_min: NotRequired[int]
    # Maximum average birth year across a company's associated persons.
    avg_birth_year_max: NotRequired[int]
    # Filter by company lifecycle status, resolved from the merged Handelsregister (SI + CD...
    legal_status: NotRequired[list[Literal['active', 'in_liquidation', 'insolvent', 'dissolved', 'deleted']]]
    # Filter to companies appearing in at least one of the selected external registries (OR...
    membership: NotRequired[list[Literal['Steuerberaterkammer', 'Wirtschaftsprueferkammer', 'bbh', 'BaFin', 'LEI']]]
    # Exact LEI (20-character ISO-17442 identifier). Matches the company whose active `comp...
    lei_code: NotRequired[str]
    # Exact USt-IdNr (German / EU VAT identification number) matched against `company_websi...
    ust_idnr: NotRequired[str]
    # Restrict to companies with (`true`) or without (`false`) a known website. Omit to ign...
    has_website: NotRequired[bool]
    # Restrict to companies with (`true`) or without (`false`) a known email. Omit to ignor...
    has_email: NotRequired[bool]
    # When `true`, additionally search the German company registers live for the keyword (`...
    fetch_realtime: NotRequired[bool]
    # Filter to companies that appear in EU public-procurement notices (TED), in the select...
    tender_role: NotRequired[list[Literal['winner', 'buyer']]]

class SubscriptionFilters(TypedDict, total=False):
    """List subscriptions."""

    # Filter to subscriptions for one company.
    eu_id: NotRequired[str]
    # Filter by subscription type.
    subscription_type: NotRequired[Literal['details', 'history', 'shareholders', 'ubo', 'doc_articles_of_association', 'doc_company_registration', 'doc_model_protocol', 'doc_shareholder_list']]
    # Filter by `recurring` or `one_time`.
    mode: NotRequired[Literal['recurring', 'one_time']]
    limit: NotRequired[int]
    offset: NotRequired[int]
