# generated by datamodel-codegen:
#   filename:  openapi.v1.json
#   timestamp: 2026-08-19T15:04:58+00:00

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypeAlias, TypedDict


class Address(TypedDict):
    city: NotRequired[str | None]
    country_code: NotRequired[str]
    federal_state: NotRequired[str | None]
    formatted_display: NotRequired[str | None]
    house_number: NotRequired[str | None]
    latitude: NotRequired[float | None]
    longitude: NotRequired[float | None]
    object: NotRequired[Literal['address']]
    postal_code: NotRequired[str | None]
    street: NotRequired[str | None]


class AutocompleteHit(TypedDict):
    display_name: str
    eu_id: str
    legal_name: str
    object: NotRequired[Literal['autocomplete_hit']]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]


class BilanzAttachment(TypedDict):
    fetched_at: NotRequired[str | None]
    file_id: str
    file_name: NotRequired[str | None]
    file_size_bytes: NotRequired[int | None]
    file_type: NotRequired[str | None]
    object: NotRequired[Literal['bilanz_attachment']]
    public_name: NotRequired[str | None]


Bundesland: TypeAlias = Literal[
    'Baden-Württemberg',
    'Bayern',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hessen',
    'Mecklenburg-Vorpommern',
    'Niedersachsen',
    'Nordrhein-Westfalen',
    'Rheinland-Pfalz',
    'Saarland',
    'Sachsen',
    'Sachsen-Anhalt',
    'Schleswig-Holstein',
    'Thüringen',
]


class BusinessBranch(TypedDict):
    name: str
    object: NotRequired[Literal['business_branch']]
    parent_name: NotRequired[str | None]
    percentage_of_total: NotRequired[float | None]
    revenue: NotRequired[float | None]
    revenue_unit: NotRequired[str | None]


class CompanyDocument(TypedDict):
    file_id: str
    file_name_de: str
    file_name_en: str
    object: NotRequired[Literal['company_document']]
    published_at: NotRequired[str | None]
    type: Literal[
        'register_extract_current',
        'register_extract_chronological',
        'shareholder_list',
        'articles_of_association',
        'company_registration',
        'model_protocol',
    ]
    type_label_de: str
    type_label_en: str
    updated_at: str


class EmployeeYear(TypedDict):
    full_time: NotRequired[int | None]
    object: NotRequired[Literal['employee_year']]
    part_time: NotRequired[int | None]
    total: NotRequired[int | None]
    year: int


class FinancialPublication(TypedDict):
    attachment: NotRequired[BilanzAttachment | None]
    fiscal_year: NotRequired[int | None]
    id: str
    object: NotRequired[Literal['financial_publication']]
    published_at: str
    title: str
    type: Literal[
        'financial_statement_annual',
        'financial_statement_consolidated',
        'financial_statement_combined',
    ]


class FinancialRow(TypedDict):
    current_value: NotRequired[float | None]
    object: NotRequired[Literal['financial_row']]
    previous_value: NotRequired[float | None]
    report_type: str
    section: NotRequired[str | None]
    subsection: NotRequired[str | None]
    subsubsection: NotRequired[str | None]
    subsubsubsection: NotRequired[str | None]
    title: str
    year: int


class Freshness(TypedDict):
    last_checked_at: NotRequired[str | None]
    object: NotRequired[Literal['freshness']]
    realtime_fetching_status: Literal[
        'success',
        'platform_unavailable',
        'documents_temporarily_unavailable',
        'file_unavailable',
        'company_unavailable',
        'realtime_fetching_disabled',
    ]


IndustrySlug: TypeAlias = Literal[
    'automotive',
    'chemicals',
    'construction',
    'consulting',
    'education',
    'energy',
    'financial_services',
    'food',
    'healthcare',
    'holdings',
    'hospitality',
    'insurance',
    'legal',
    'logistics',
    'manufacturing',
    'media',
    'mining',
    'public_sector',
    'technology',
    'telecom',
    'trade',
]


class InsolvencyBlock(TypedDict):
    case_number: NotRequired[str | None]
    court_name: NotRequired[str | None]
    current_status: NotRequired[
        Literal[
            'active',
            'preliminary',
            'in_insolvency',
            'rejected',
            'terminated',
            'in_liquidation',
            'dissolved',
        ]
    ]
    has_insolvency: NotRequired[bool]
    has_liquidator: NotRequired[bool]
    is_dissolved: NotRequired[bool]
    most_recent_event_at: NotRequired[str | None]
    object: NotRequired[Literal['insolvency_status']]
    self_administration: NotRequired[bool]


LegalStatus: TypeAlias = Literal[
    'active', 'in_liquidation', 'insolvent', 'dissolved', 'deleted'
]


class LegalStatusEvent(TypedDict):
    case_number: NotRequired[str | None]
    category: str
    court_name: NotRequired[str | None]
    decision_date: NotRequired[str | None]
    dissolved: NotRequired[bool]
    effective_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    event_date: NotRequired[str | None]
    ex_officio: NotRequired[bool]
    legal_basis: NotRequired[list[str]]
    object: NotRequired[Literal['legal_status_event']]
    self_administration: NotRequired[bool]
    sources: NotRequired[list[Literal['si', 'cd', 'portal']]]


class LeiRelative(TypedDict):
    city: NotRequired[str | None]
    country_code: NotRequired[str | None]
    display_name: NotRequired[str | None]
    eu_id: NotRequired[str | None]
    legal_name: NotRequired[str | None]
    lei_code: str
    object: NotRequired[Literal['lei_relative']]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    relationship: str


class LocalizedText(TypedDict):
    de: NotRequired[str | None]
    en: NotRequired[str | None]
    object: NotRequired[Literal['localized_text']]
    translation_source: NotRequired[
        Literal['original', 'human', 'machine', 'passthrough']
    ]


Membership: TypeAlias = Literal[
    'Steuerberaterkammer', 'Wirtschaftsprueferkammer', 'bbh', 'BaFin', 'LEI'
]


class Money(TypedDict):
    amount: NotRequired[float | None]
    currency: NotRequired[str]
    object: NotRequired[Literal['money']]


NotificationCadence: TypeAlias = Literal['immediately', 'daily', 'weekly', 'monthly']


NotificationLanguage: TypeAlias = Literal['en', 'de']


NotificationType: TypeAlias = Literal['webhook', 'email']


class OrganizationRef(TypedDict):
    country_code: NotRequired[str | None]
    display_name: str
    eu_id: NotRequired[str | None]
    legal_name: str
    lei_code: NotRequired[str | None]
    object: NotRequired[Literal['organization_ref']]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    registered_seat: NotRequired[str | None]


class PaginationInfo(TypedDict):
    has_more: NotRequired[bool]
    next_cursor: NotRequired[str | None]
    object: NotRequired[Literal['pagination']]
    previous_cursor: NotRequired[str | None]
    total_approx: NotRequired[int | None]
    total_is_capped: NotRequired[bool]


class Person(TypedDict):
    age: NotRequired[int | None]
    city: NotRequired[str | None]
    date_of_birth: NotRequired[str | None]
    first_name: NotRequired[str | None]
    full_name: str
    last_name: NotRequired[str | None]
    middle_name: NotRequired[str | None]
    object: NotRequired[Literal['person']]
    title: NotRequired[str | None]


class PotentialBeneficialOwner(TypedDict):
    chain_positions: int
    effective_share_percent: float
    object: NotRequired[Literal['potential_beneficial_owner']]
    organization: OrganizationRef
    unresolved_reason: Literal[
        'foreign_org', 'unlisted_org', 'cap_table_not_filed', 'max_depth_reached'
    ]


class Error(TypedDict):
    code: NotRequired[str]
    path: NotRequired[str]


class Problem(TypedDict):
    detail: NotRequired[str]
    errors: NotRequired[list[Error]]
    instance: NotRequired[str]
    request_id: NotRequired[str]
    status: int
    title: str
    type: str


Rechtsform: TypeAlias = Literal[
    'GmbH',
    'KG',
    'e.K.; e.Kfm.; e.Kfr.',
    'eGbR',
    'UG',
    'GmbH & Co. KG',
    'OHG',
    'PartG',
    'AG',
    'eG',
    'ausl. Rechtsform',
    'Rechtsform ausländischen Rechts HRB',
    'e.V.',
    'gGmbH',
    'UG & Co. KG',
    'SE',
    'EWIV',
    'KGaA',
    'sonst. juristische Person, d. im HRA eingetragen ist',
    'VVaG',
    'SCE',
]


RegisterCourt: TypeAlias = Literal[
    'Aachen',
    'Ahaus',
    'Amberg',
    'Ansbach',
    'Arnsberg',
    'Aschaffenburg',
    'Augsburg',
    'Aurich',
    'Bad Hersfeld',
    'Bad Homburg v.d.H.',
    'Bad Kreuznach',
    'Bad Oeynhausen',
    'Bamberg',
    'Bayreuth',
    'Berlin (Charlottenburg)',
    'Bielefeld',
    'Bocholt',
    'Bochum',
    'Bonn',
    'Borken',
    'Braunschweig',
    'Bremen',
    'Bremerhaven',
    'Chemnitz',
    'Coburg',
    'Coesfeld',
    'Cottbus',
    'Darmstadt',
    'Deggendorf',
    'Dortmund',
    'Dresden',
    'Duisburg',
    'Dülmen',
    'Düren',
    'Düsseldorf',
    'Eschwege',
    'Essen',
    'Flensburg',
    'Frankfurt am Main',
    'Frankfurt/Oder',
    'Freiburg',
    'Friedberg',
    'Fritzlar',
    'Fulda',
    'Fürth',
    'Gelsenkirchen',
    'Gießen',
    'Gronau',
    'Göttingen',
    'Gütersloh',
    'Hagen',
    'Hamburg',
    'Hamm',
    'Hanau',
    'Hannover',
    'Hildesheim',
    'Hof',
    'Homburg',
    'Ingolstadt',
    'Iserlohn',
    'Jena',
    'Kaiserslautern',
    'Kassel',
    'Kempten (Allgäu)',
    'Kerpen',
    'Kiel',
    'Kleve',
    'Koblenz',
    'Korbach',
    'Krefeld',
    'Köln',
    'Königstein',
    'Landau',
    'Landshut',
    'Langenfeld',
    'Lebach',
    'Leipzig',
    'Lemgo',
    'Limburg',
    'Ludwigshafen a.Rhein (Ludwigshafen)',
    'Lübeck',
    'Lüdinghausen',
    'Lüneburg',
    'Mainz',
    'Mannheim',
    'Marburg',
    'Memmingen',
    'Merzig',
    'Montabaur',
    'Mönchengladbach',
    'München',
    'Münster',
    'Neubrandenburg',
    'Neunkirchen',
    'Neuruppin',
    'Neuss',
    'Nürnberg',
    'Offenbach am Main',
    'Oldenburg (Oldenburg)',
    'Osnabrück',
    'Ottweiler',
    'Paderborn',
    'Passau',
    'Pinneberg',
    'Potsdam',
    'Recklinghausen',
    'Regensburg',
    'Rostock',
    'Saarbrücken',
    'Saarlouis',
    'Schleiden',
    'Schweinfurt',
    'Schwerin',
    'Siegburg',
    'Siegen',
    'St. Ingbert (St Ingbert)',
    'St. Wendel (St Wendel)',
    'Stadthagen',
    'Steinfurt',
    'Stendal',
    'Stralsund',
    'Straubing',
    'Stuttgart',
    'Tostedt',
    'Traunstein',
    'Ulm',
    'Völklingen',
    'Walsrode',
    'Weiden i. d. OPf.',
    'Wetzlar',
    'Wiesbaden',
    'Wittlich',
    'Wuppertal',
    'Würzburg',
    'Zweibrücken',
]


class RegisterHistoryEvent(TypedDict):
    data: NotRequired[dict[str, Any]]
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    object: NotRequired[Literal['register_history_event']]


RegisterType: TypeAlias = Literal['HRA', 'HRB', 'GnR', 'PR', 'VR', 'GsR']


class RelatedCompany(TypedDict):
    bilanz_type: NotRequired[str | None]
    display_name: str
    eu_id: NotRequired[str | None]
    legal_name: str
    object: NotRequired[Literal['related_company']]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    registered_seat: NotRequired[str | None]
    reporting_year: NotRequired[int | None]


class RelationshipsBlock(TypedDict):
    object: NotRequired[Literal['company_relationships']]
    parent_company: NotRequired[RelatedCompany | None]
    subsidiaries: NotRequired[list[RelatedCompany]]


class SearchHit(TypedDict):
    address: NotRequired[Address | None]
    cpv_award_codes: NotRequired[list[str]]
    display_name: str
    employee_count: NotRequired[int | None]
    employee_count_year: NotRequired[int | None]
    eu_id: str
    financial_year: NotRequired[int | None]
    founded_at: NotRequired[str | None]
    legal_name: str
    legal_status: NotRequired[
        Literal['active', 'in_liquidation', 'insolvent', 'dissolved', 'deleted']
    ]
    object: NotRequired[Literal['search_hit']]
    profit: NotRequired[float | None]
    profit_year: NotRequired[int | None]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    revenue: NotRequired[float | None]
    revenue_year: NotRequired[int | None]
    total_assets: NotRequired[float | None]
    total_assets_year: NotRequired[int | None]
    website: NotRequired[str | None]


class SearchResponse(TypedDict):
    data: NotRequired[list[SearchHit]]
    execution_time_ms: NotRequired[float | None]
    filters_echo: NotRequired[dict[str, Any]]
    freshness: NotRequired[Freshness]
    object: NotRequired[Literal['list']]
    pagination: NotRequired[PaginationInfo]


class Shareholder(TypedDict):
    display_name: str
    object: NotRequired[Literal['shareholder']]
    organization: NotRequired[OrganizationRef | None]
    party_type: Literal['natural_person', 'organization']
    person: NotRequired[Person | None]
    share_percent: NotRequired[float | None]
    shares_nominal: NotRequired[Money | None]
    total_shares: NotRequired[float | None]


class ShareholdersCoverage(TypedDict):
    object: NotRequired[Literal['shareholders_coverage']]
    status: NotRequired[
        Literal['available', 'not_applicable', 'not_filed', 'token_limit_reached']
    ]


class ShareholdersSnapshot(TypedDict):
    object: NotRequired[Literal['shareholders_snapshot']]
    shareholders: NotRequired[list[Shareholder]]


class SocialProfile(TypedDict):
    object: NotRequired[Literal['social_profile']]
    platform: str
    url: str


Sort: TypeAlias = Literal[
    'name',
    'city',
    'bundesland',
    'industry',
    'revenue',
    'profit',
    'employee_count',
    'cpv',
]


SortDirection: TypeAlias = Literal['asc', 'desc']


class SubscriptionEvent(TypedDict):
    change_detected: bool
    delivery_attempted: bool
    delivery_attempts: int
    delivery_duration_ms: NotRequired[int | None]
    delivery_error: NotRequired[str | None]
    delivery_http_status: NotRequired[int | None]
    delivery_response_excerpt: NotRequired[str | None]
    event_id: str
    finished_at: NotRequired[str | None]
    notification_type: NotificationType | None
    object: NotRequired[Literal['subscription_event']]
    outcome: str
    publish_date_previous: NotRequired[str | None]
    publish_date_seen: NotRequired[str | None]
    request_body: NotRequired[dict[str, Any] | None]
    request_signature: NotRequired[str | None]
    request_timestamp: NotRequired[str | None]
    request_url: NotRequired[str | None]
    scrape_error_message: NotRequired[str | None]
    started_at: str


class SubscriptionEventList(TypedDict):
    items: NotRequired[list[SubscriptionEvent]]
    object: NotRequired[Literal['list']]


class SubscriptionEventResendResponse(TypedDict):
    duration_ms: int
    error: NotRequired[str | None]
    event: SubscriptionEvent
    http_status: NotRequired[int | None]
    object: NotRequired[Literal['subscription_event_resend']]
    succeeded: bool


class SubscriptionEventStatus(TypedDict):
    change_detected: bool
    delivery_attempted: bool
    delivery_attempts: int
    delivery_duration_ms: NotRequired[int | None]
    delivery_error: NotRequired[str | None]
    delivery_http_status: NotRequired[int | None]
    event_id: str
    finished_at: NotRequired[str | None]
    object: NotRequired[Literal['subscription_event_status']]
    outcome: str
    publish_date_previous: NotRequired[str | None]
    publish_date_seen: NotRequired[str | None]
    scrape_error_message: NotRequired[str | None]
    started_at: str


SubscriptionMode: TypeAlias = Literal['recurring', 'one_time']


SubscriptionType: TypeAlias = Literal[
    'details',
    'history',
    'shareholders',
    'ubo',
    'doc_articles_of_association',
    'doc_company_registration',
    'doc_model_protocol',
    'doc_shareholder_list',
]


TenderRole: TypeAlias = Literal['winner', 'buyer']


class UboCoverage(TypedDict):
    object: NotRequired[Literal['ubo_coverage']]
    reason: NotRequired[str | None]
    status: NotRequired[Literal['available', 'partial', 'not_applicable', 'not_filed']]


class UboEdge(TypedDict):
    object: NotRequired[Literal['ubo_edge']]
    share_percent: NotRequired[float | None]
    source_id: str
    target_id: str


class UboNode(TypedDict):
    eu_id: NotRequired[str | None]
    id: str
    is_root: NotRequired[bool]
    is_unresolved: NotRequired[bool]
    node_type: Literal['company', 'person', 'organization_unresolved']
    object: NotRequired[Literal['ubo_node']]
    organization: NotRequired[OrganizationRef | None]
    person: NotRequired[Person | None]
    unresolved_reason: NotRequired[
        Literal[
            'foreign_org', 'unlisted_org', 'cap_table_not_filed', 'max_depth_reached'
        ]
        | None
    ]


class WebhookTestAttempt(TypedDict):
    attempt: int
    duration_ms: int
    error: NotRequired[str | None]
    http_status: NotRequired[int | None]
    object: NotRequired[Literal['webhook_test_attempt']]
    response_excerpt: NotRequired[str | None]
    sent_signature_header: str
    sent_timestamp_header: str
    succeeded: bool


WebhookTestDeliveryScenario: TypeAlias = Literal[
    'success', 'retry_delivery', 'bad_signature', 'stale_timestamp'
]


class WebsiteEntry(TypedDict):
    domain: str
    impressum_url: NotRequired[str | None]
    is_primary: NotRequired[bool]
    object: NotRequired[Literal['company_website']]
    verification: NotRequired[str]


class Wz2025Score(TypedDict):
    code: str
    description: NotRequired[str | None]
    object: NotRequired[Literal['wz_2025_score']]
    score: NotRequired[float | None]
    section: NotRequired[str | None]


class AiInsightsBlock(TypedDict):
    object: NotRequired[Literal['ai_insights']]
    outlook: NotRequired[LocalizedText | None]
    summary: NotRequired[LocalizedText | None]


class AutocompleteResponse(TypedDict):
    data: NotRequired[list[AutocompleteHit]]
    filters_echo: NotRequired[dict[str, Any]]
    freshness: NotRequired[Freshness]
    object: NotRequired[Literal['list']]
    pagination: NotRequired[PaginationInfo]


class BeneficialOwner(TypedDict):
    effective_share_percent: float
    node_id: str
    object: NotRequired[Literal['beneficial_owner']]
    person: Person


class BusinessBlock(TypedDict):
    business_branches: NotRequired[list[BusinessBranch]]
    object: NotRequired[Literal['company_business']]
    opportunity_keywords: NotRequired[list[str]]
    products: NotRequired[list[str]]
    risk_keywords: NotRequired[list[str]]


class CompanyDocumentDownload(TypedDict):
    download_url: str
    download_url_expires_at: str
    file_id: str
    file_name_de: str
    file_name_en: str
    freshness: Freshness
    object: NotRequired[Literal['company_document_download']]
    published_at: NotRequired[str | None]
    type: Literal[
        'register_extract_current',
        'register_extract_chronological',
        'shareholder_list',
        'articles_of_association',
        'company_registration',
        'model_protocol',
    ]
    type_label_de: str
    type_label_en: str
    updated_at: str


class CompanyHistory(TypedDict):
    board_members: NotRequired[list[RegisterHistoryEvent]]
    company_status: NotRequired[str | None]
    current_board: NotRequired[list[dict[str, Any]]]
    erste_eintragung: NotRequired[RegisterHistoryEvent | None]
    eu_id: str
    firma: NotRequired[list[RegisterHistoryEvent]]
    freshness: Freshness
    gegenstand: NotRequired[list[RegisterHistoryEvent]]
    geschaeftsanschrift: NotRequired[list[RegisterHistoryEvent]]
    kapital: NotRequired[list[RegisterHistoryEvent]]
    kommanditisten: NotRequired[list[RegisterHistoryEvent]]
    legal_status_events: NotRequired[list[LegalStatusEvent]]
    object: NotRequired[Literal['company_history']]
    rechtsform: NotRequired[list[RegisterHistoryEvent]]
    satzung_events: NotRequired[list[RegisterHistoryEvent]]
    sitz: NotRequired[list[RegisterHistoryEvent]]
    zweigniederlassungen: NotRequired[list[RegisterHistoryEvent]]


class ContactBlock(TypedDict):
    impressum_url: NotRequired[str | None]
    object: NotRequired[Literal['company_contact']]
    social_profiles: NotRequired[list[SocialProfile]]
    website: NotRequired[str | None]
    websites: NotRequired[list[WebsiteEntry]]


class EmployeeHistoryBlock(TypedDict):
    object: NotRequired[Literal['employee_history']]
    series: NotRequired[list[EmployeeYear]]


class FinancialMetric(TypedDict):
    balance_sheet_total: NotRequired[Money | None]
    liabilities_and_equity_total: NotRequired[Money | None]
    object: NotRequired[Literal['financial_metric']]
    profit: NotRequired[Money | None]
    revenue: NotRequired[Money | None]
    year: int


class FinancialSummaryBlock(TypedDict):
    latest_employee_count: NotRequired[int | None]
    latest_fiscal_year: NotRequired[int | None]
    latest_total_assets: NotRequired[Money | None]
    latest_total_liabilities_and_equity: NotRequired[Money | None]
    object: NotRequired[Literal['financial_summary']]


class IndustryBlock(TypedDict):
    object: NotRequired[Literal['company_industry']]
    primary_wz_2025_code: NotRequired[str | None]
    wz_2025_codes: NotRequired[list[Wz2025Score]]


class LeiGraphBlock(TypedDict):
    direct_children: NotRequired[list[LeiRelative]]
    direct_parent: NotRequired[LeiRelative | None]
    lei_code: NotRequired[str | None]
    object: NotRequired[Literal['lei_graph']]


class Member(TypedDict):
    object: NotRequired[Literal['member']]
    organization: NotRequired[OrganizationRef | None]
    person: NotRequired[Person | None]
    role: NotRequired[str | None]
    role_code: NotRequired[str | None]


class ShareholdersReport(TypedDict):
    as_of_snapshot: NotRequired[ShareholdersSnapshot | None]
    coverage: ShareholdersCoverage
    eu_id: str
    freshness: Freshness
    object: NotRequired[Literal['shareholders_report']]


class Subscription(TypedDict):
    cadence: NotificationCadence | None
    cadence_seconds: int
    created_at: str
    eu_id: str
    id: str
    language: NotRequired[NotificationLanguage]
    last_attempted_at: NotRequired[str | None]
    last_event: NotRequired[SubscriptionEventStatus | None]
    latest_succeeded_publish_date: NotRequired[str | None]
    mode: SubscriptionMode
    notification_type: NotificationType | None
    object: NotRequired[Literal['subscription']]
    recipient_email: NotRequired[str | None]
    subscription_end_date: NotRequired[str | None]
    subscription_type: SubscriptionType
    updated_at: str
    webhook_url: NotRequired[str | None]


class SubscriptionCreateRequest(TypedDict):
    cadence: NotRequired[NotificationCadence]
    eu_id: str
    language: NotRequired[NotificationLanguage]
    mode: NotRequired[SubscriptionMode]
    notification_type: NotRequired[NotificationType | None]
    recipient_email: NotRequired[str | None]
    subscription_end_date: NotRequired[str | None]
    subscription_type: SubscriptionType
    webhook_url: NotRequired[str | None]


class SubscriptionCreated(TypedDict):
    cadence: NotificationCadence | None
    cadence_seconds: int
    created_at: str
    eu_id: str
    id: str
    language: NotRequired[NotificationLanguage]
    last_attempted_at: NotRequired[str | None]
    last_event: NotRequired[SubscriptionEventStatus | None]
    latest_succeeded_publish_date: NotRequired[str | None]
    mode: SubscriptionMode
    notification_type: NotificationType | None
    object: NotRequired[Literal['subscription_created']]
    recipient_email: NotRequired[str | None]
    subscription_end_date: NotRequired[str | None]
    subscription_type: SubscriptionType
    updated_at: str
    webhook_secret: NotRequired[str | None]
    webhook_url: NotRequired[str | None]


class SubscriptionList(TypedDict):
    items: NotRequired[list[Subscription]]
    object: NotRequired[Literal['list']]


class SubscriptionTestRequest(TypedDict):
    delivery_scenario: NotRequired[WebhookTestDeliveryScenario]
    eu_id: str
    language: NotRequired[NotificationLanguage]
    notification_type: NotificationType
    recipient_email: NotRequired[str | None]
    scenario: NotRequired[Literal['change']]
    subscription_type: SubscriptionType
    webhook_url: NotRequired[str | None]


class SubscriptionTestResponse(TypedDict):
    attempts: NotRequired[list[WebhookTestAttempt] | None]
    delivery_scenario: NotRequired[WebhookTestDeliveryScenario | None]
    duration_ms: int
    notification_type: NotificationType
    object: NotRequired[Literal['subscription_test_result']]
    receiver_error: NotRequired[str | None]
    receiver_http_status: NotRequired[int | None]
    receiver_response_excerpt: NotRequired[str | None]
    receiver_succeeded: bool
    recipient_email: NotRequired[str | None]
    sent_body: NotRequired[dict[str, Any] | None]
    sent_body_html: NotRequired[str | None]
    sent_event_id: NotRequired[str | None]
    sent_event_type: NotRequired[str | None]
    sent_signature_header: NotRequired[str | None]
    sent_subject: NotRequired[str | None]
    sent_timestamp_header: NotRequired[str | None]
    webhook_secret: NotRequired[str | None]
    webhook_url: NotRequired[str | None]


class UboGraph(TypedDict):
    edges: NotRequired[list[UboEdge]]
    nodes: NotRequired[list[UboNode]]
    object: NotRequired[Literal['ubo_graph']]
    root_id: str


class UboReport(TypedDict):
    beneficial_owners: NotRequired[list[BeneficialOwner]]
    coverage: UboCoverage
    eu_id: str
    freshness: Freshness
    graph: UboGraph
    has_unresolved_branches: NotRequired[bool]
    object: NotRequired[Literal['ubo_report']]
    potential_beneficial_owners: NotRequired[list[PotentialBeneficialOwner]]


class CompanyDetail(TypedDict):
    address: NotRequired[Address | None]
    ai_insights: NotRequired[AiInsightsBlock | None]
    business_info: NotRequired[BusinessBlock | None]
    business_purpose: NotRequired[str | None]
    contact: ContactBlock
    display_name: str
    documents: NotRequired[list[CompanyDocument]]
    elf_code: NotRequired[str | None]
    eu_id: str
    financial_summary: NotRequired[FinancialSummaryBlock | None]
    first_register_entry_at: NotRequired[str | None]
    founding_document_date: NotRequired[str | None]
    freshness: Freshness
    industry_categorization: IndustryBlock
    insolvency: NotRequired[InsolvencyBlock | None]
    latest_register_entry_date: NotRequired[str | None]
    legal_form: NotRequired[str | None]
    legal_name: NotRequired[str | None]
    lei_graph: NotRequired[LeiGraphBlock | None]
    management: NotRequired[list[Member]]
    object: NotRequired[Literal['company']]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    registered_seat: NotRequired[str | None]
    share_capital: NotRequired[Money | None]
    status: NotRequired[
        Literal['active', 'in_liquidation', 'insolvent', 'dissolved', 'deleted']
    ]
    ust_id_nr: NotRequired[str | None]
    wirtschafts_id_nr: NotRequired[str | None]


class FinancialHistoryBlock(TypedDict):
    assets: NotRequired[list[FinancialRow]]
    liabilities_and_equity: NotRequired[list[FinancialRow]]
    metrics: NotRequired[list[FinancialMetric]]
    object: NotRequired[Literal['financial_history']]
    profit_and_loss: NotRequired[list[FinancialRow]]


class CompanyFinancials(TypedDict):
    employee_history: EmployeeHistoryBlock
    financial_publications: NotRequired[list[FinancialPublication]]
    freshness: Freshness
    history: FinancialHistoryBlock
    id: str
    object: NotRequired[Literal['company_financials']]
    relationships: NotRequired[RelationshipsBlock | None]
    summary: NotRequired[FinancialSummaryBlock | None]
