# generated by datamodel-codegen:
#   filename:  openapi.v1.json

from __future__ import annotations
from typing import Any, Literal, NotRequired, TypeAlias, TypedDict


class Address(TypedDict):
    city: NotRequired[str | None]
    country_code: NotRequired[str]
    federal_state: NotRequired[str | None]
    formatted_display: NotRequired[str | None]
    house_number: NotRequired[str | None]
    latitude: NotRequired[float | None]
    longitude: NotRequired[float | None]
    object: NotRequired[Literal['address']]
    postal_code: NotRequired[str | None]
    street: NotRequired[str | None]


class AddressEntry(TypedDict):
    address: Address
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    object: NotRequired[Literal['address_entry']]


class ArticlesEntry(TypedDict):
    change: Literal['created', 'amended']
    document_date: NotRequired[str | None]
    document_type: NotRequired[str | None]
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    object: NotRequired[Literal['articles_entry']]


class AutocompleteHit(TypedDict):
    country_code: Literal['DE', 'CH']
    display_name: str
    eu_id: str
    legal_name: str
    object: NotRequired[Literal['autocomplete_hit']]
    register_canton: NotRequired[str | None]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    uid: NotRequired[str | None]


class BilanzAttachment(TypedDict):
    fetched_at: NotRequired[str | None]
    file_id: str
    file_name: NotRequired[str | None]
    file_size_bytes: NotRequired[int | None]
    file_type: NotRequired[str | None]
    object: NotRequired[Literal['bilanz_attachment']]
    public_name: NotRequired[str | None]


class BoardRepresentation(TypedDict):
    excluded: NotRequired[bool]
    exempt_from_self_dealing_ban: NotRequired[bool]
    joint: NotRequired[bool]
    joint_with: NotRequired[str | None]
    object: NotRequired[Literal['board_representation']]
    sole: NotRequired[bool]


Bundesland: TypeAlias = Literal[
    'Baden-Württemberg',
    'Bayern',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hessen',
    'Mecklenburg-Vorpommern',
    'Niedersachsen',
    'Nordrhein-Westfalen',
    'Rheinland-Pfalz',
    'Saarland',
    'Sachsen',
    'Sachsen-Anhalt',
    'Schleswig-Holstein',
    'Thüringen',
]


class BusinessBranch(TypedDict):
    name: str
    object: NotRequired[Literal['business_branch']]
    parent_name: NotRequired[str | None]
    percentage_of_total: NotRequired[float | None]
    revenue: NotRequired[float | None]
    revenue_unit: NotRequired[str | None]


Canton: TypeAlias = Literal[
    'AG',
    'AI',
    'AR',
    'BE',
    'BL',
    'BS',
    'FR',
    'GE',
    'GL',
    'GR',
    'JU',
    'LU',
    'NE',
    'NW',
    'OW',
    'SG',
    'SH',
    'SO',
    'SZ',
    'TG',
    'TI',
    'UR',
    'VD',
    'VS',
    'ZG',
    'ZH',
]


class CompanyDocument(TypedDict):
    file_id: str
    file_name_de: str
    file_name_en: str
    is_outdated: NotRequired[bool]
    object: NotRequired[Literal['company_document']]
    published_at: NotRequired[str | None]
    type: Literal[
        'register_extract_current',
        'register_extract_chronological',
        'shareholder_list',
        'articles_of_association',
        'company_registration',
        'model_protocol',
    ]
    type_label_de: str
    type_label_en: str
    updated_at: str


class CompanyDocumentListItem(TypedDict):
    document_date: NotRequired[str | None]
    document_id: NotRequired[str | None]
    fetched_at: NotRequired[str | None]
    file_id: NotRequired[str | None]
    is_latest: bool
    is_outdated: NotRequired[bool]
    label: NotRequired[str | None]
    object: NotRequired[Literal['company_document_listing']]
    published_at: NotRequired[str | None]
    stored: bool
    type: Literal[
        'register_extract_current',
        'register_extract_chronological',
        'shareholder_list',
        'articles_of_association',
        'company_registration',
        'model_protocol',
    ]
    type_label_de: str
    type_label_en: str


class CompanyListSummary(TypedDict):
    alerts_enabled: NotRequired[bool]
    company_count: NotRequired[int]
    created_at: str
    is_shared: NotRequired[bool]
    list_id: int
    name: str
    object: NotRequired[Literal['company_list']]
    updated_at: str


CompanySize: TypeAlias = Literal['kleinst', 'klein', 'mittelgross']


Country: TypeAlias = Literal['DE', 'CH']


class DocumentsCoverage(TypedDict):
    object: NotRequired[Literal['documents_coverage']]
    reason: NotRequired[str | None]
    status: Literal['available', 'not_applicable']


class EmployeeYear(TypedDict):
    full_time: NotRequired[int | None]
    object: NotRequired[Literal['employee_year']]
    part_time: NotRequired[int | None]
    total: NotRequired[int | None]
    year: int


class FinancialPublication(TypedDict):
    attachment: NotRequired[BilanzAttachment | None]
    fiscal_year: NotRequired[int | None]
    id: str
    object: NotRequired[Literal['financial_publication']]
    published_at: str
    title: str
    type: Literal[
        'financial_statement_annual',
        'financial_statement_consolidated',
        'financial_statement_combined',
    ]


class FinancialRow(TypedDict):
    current_value: NotRequired[float | None]
    object: NotRequired[Literal['financial_row']]
    previous_value: NotRequired[float | None]
    report_type: str
    section: NotRequired[str | None]
    subsection: NotRequired[str | None]
    subsubsection: NotRequired[str | None]
    subsubsubsection: NotRequired[str | None]
    title: str
    year: int


class FirstRegisterEntry(TypedDict):
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    first_registered_date: NotRequired[str | None]
    founding_document_date: NotRequired[str | None]
    founding_document_type: NotRequired[str | None]
    object: NotRequired[Literal['first_register_entry']]
    origin: NotRequired[
        Literal['founding', 'transfer', 'conversion', 'charter_predates']
    ]


class FounderRecordItem(TypedDict):
    birth_year: NotRequired[int | None]
    entry_date: NotRequired[str | None]
    first_name: NotRequired[str | None]
    last_name: NotRequired[str | None]
    object: NotRequired[Literal['founder']]
    role: NotRequired[str | None]
    share_percent: NotRequired[float | None]
    still_serving: NotRequired[bool]


class Freshness(TypedDict):
    last_checked_at: NotRequired[str | None]
    object: NotRequired[Literal['freshness']]
    realtime_fetching_status: Literal[
        'success',
        'platform_unavailable',
        'documents_temporarily_unavailable',
        'file_unavailable',
        'company_unavailable',
        'realtime_fetching_disabled',
    ]


class HistoryBranch(TypedDict):
    address: NotRequired[str | None]
    city: NotRequired[str | None]
    name: NotRequired[str | None]
    object: NotRequired[Literal['branch']]
    register_court: NotRequired[str | None]
    register_number: NotRequired[str | None]
    register_type: NotRequired[str | None]


class HistoryCoverage(TypedDict):
    object: NotRequired[Literal['history_coverage']]
    reason: NotRequired[str | None]
    status: Literal['available', 'not_available']


IndustrySlug: TypeAlias = Literal[
    'automotive',
    'chemicals',
    'construction',
    'consulting',
    'education',
    'energy',
    'financial_services',
    'food',
    'healthcare',
    'holdings',
    'hospitality',
    'insurance',
    'legal',
    'logistics',
    'manufacturing',
    'media',
    'mining',
    'public_sector',
    'technology',
    'telecom',
    'trade',
]


class InsolvencyBlock(TypedDict):
    case_number: NotRequired[str | None]
    court_name: NotRequired[str | None]
    current_status: NotRequired[
        Literal[
            'active',
            'preliminary',
            'in_insolvency',
            'rejected',
            'terminated',
            'in_liquidation',
            'dissolved',
        ]
    ]
    has_insolvency: NotRequired[bool]
    has_liquidator: NotRequired[bool]
    is_dissolved: NotRequired[bool]
    most_recent_event_at: NotRequired[str | None]
    object: NotRequired[Literal['insolvency_status']]
    self_administration: NotRequired[bool]


class LegalFormEntry(TypedDict):
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    legal_form: str
    object: NotRequired[Literal['legal_form_entry']]
    previous_legal_form: NotRequired[str | None]


LegalStatus: TypeAlias = Literal[
    'active', 'in_liquidation', 'insolvent', 'dissolved', 'deleted'
]


class LegalStatusEvent(TypedDict):
    case_number: NotRequired[str | None]
    category: str
    court_name: NotRequired[str | None]
    decision_date: NotRequired[str | None]
    dissolved: NotRequired[bool]
    effective_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    event_date: NotRequired[str | None]
    ex_officio: NotRequired[bool]
    legal_basis: NotRequired[list[str]]
    object: NotRequired[Literal['legal_status_event']]
    self_administration: NotRequired[bool]
    sources: NotRequired[list[Literal['si', 'cd', 'portal']]]


class LeiRelative(TypedDict):
    city: NotRequired[str | None]
    country_code: NotRequired[str | None]
    display_name: NotRequired[str | None]
    eu_id: NotRequired[str | None]
    legal_name: NotRequired[str | None]
    lei_code: str
    object: NotRequired[Literal['lei_relative']]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    relationship: str


class LocalizedText(TypedDict):
    de: NotRequired[str | None]
    en: NotRequired[str | None]
    object: NotRequired[Literal['localized_text']]
    translation_source: NotRequired[
        Literal['original', 'human', 'machine', 'passthrough'] | None
    ]


Membership: TypeAlias = Literal[
    'Steuerberaterkammer', 'Wirtschaftsprueferkammer', 'bbh', 'BaFin', 'LEI'
]


class Money(TypedDict):
    amount: NotRequired[float | None]
    currency: NotRequired[str]
    object: NotRequired[Literal['money']]


class NameEntry(TypedDict):
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    name: str
    object: NotRequired[Literal['name_entry']]


NotificationCadence: TypeAlias = Literal['immediately', 'daily', 'weekly', 'monthly']


NotificationLanguage: TypeAlias = Literal['en', 'de']


NotificationType: TypeAlias = Literal['webhook', 'email']


class OrganizationRef(TypedDict):
    country_code: NotRequired[str | None]
    display_name: str
    eu_id: NotRequired[str | None]
    legal_name: str
    lei_code: NotRequired[str | None]
    object: NotRequired[Literal['organization_ref']]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    registered_seat: NotRequired[str | None]


class PaginationInfo(TypedDict):
    has_more: NotRequired[bool]
    next_cursor: NotRequired[str | None]
    object: NotRequired[Literal['pagination']]
    previous_cursor: NotRequired[str | None]
    total_approx: NotRequired[int | None]
    total_is_capped: NotRequired[bool]


class Person(TypedDict):
    age: NotRequired[int | None]
    city: NotRequired[str | None]
    date_of_birth: NotRequired[str | None]
    first_name: NotRequired[str | None]
    full_name: str
    last_name: NotRequired[str | None]
    middle_name: NotRequired[str | None]
    object: NotRequired[Literal['person']]
    title: NotRequired[str | None]


class PotentialBeneficialOwner(TypedDict):
    chain_positions: int
    effective_share_percent: float
    object: NotRequired[Literal['potential_beneficial_owner']]
    organization: OrganizationRef
    unresolved_reason: Literal[
        'foreign_org', 'unlisted_org', 'cap_table_not_filed', 'max_depth_reached'
    ]


class Error(TypedDict):
    message: str
    param: str


class Problem(TypedDict):
    detail: NotRequired[str]
    errors: NotRequired[list[Error]]
    instance: NotRequired[str]
    request_id: str
    status: int
    title: str
    type: str


class PurposeEntry(TypedDict):
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    object: NotRequired[Literal['purpose_entry']]
    purpose: str


Rechtsform: TypeAlias = Literal[
    'GmbH',
    'KG',
    'e.K.',
    'eGbR',
    'UG',
    'GmbH & Co. KG',
    'OHG',
    'PartG',
    'e.V.',
    'AG',
    'eG',
    'ausländische Rechtsform (HRB)',
    'gGmbH',
    'UG & Co. KG',
    'ausländische Rechtsform',
    'SE',
    'sonstige juristische Person',
    'EWIV',
    'KGaA',
    'Ltd. & Co. KG',
    'sonstige juristische Person (HRA)',
    'GmbH & Co. OHG',
    'VVaG',
    'SE & Co. KG',
    'ausländische Rechtsform (HRA)',
    'AG & Co. KG',
    'ausländische Rechtsform (PR)',
    'SCE',
    'ausländische Rechtsform (GnR)',
    'Stiftung & Co. KG',
    'eG & Co. KG',
    'Einzelunternehmen (CH)',
    'Kollektivgesellschaft (CH)',
    'Kommanditgesellschaft (CH)',
    'Kommanditaktiengesellschaft (CH)',
    'AG (CH)',
    'GmbH (CH)',
    'Genossenschaft (CH)',
    'Verein (CH)',
    'Stiftung (CH)',
    'Zweigniederlassung ausl. Ges. (CH)',
    'Besondere Rechtsform (CH)',
    'KmGK (CH)',
    'SICAV (CH)',
    'SICAF (CH)',
    'Institut des öffentlichen Rechts (CH)',
    'Nichtkaufmännische Prokura (CH)',
    'Gemeinderschaft (CH)',
    'Zweigniederlassung (CH)',
]


RegisterCourt: TypeAlias = Literal[
    'Aachen',
    'Ahaus',
    'Amberg',
    'Ansbach',
    'Arnsberg',
    'Aschaffenburg',
    'Augsburg',
    'Aurich',
    'Bad Hersfeld',
    'Bad Homburg v.d.H.',
    'Bad Kreuznach',
    'Bad Oeynhausen',
    'Bamberg',
    'Bayreuth',
    'Berlin (Charlottenburg)',
    'Bielefeld',
    'Bocholt',
    'Bochum',
    'Bonn',
    'Borken',
    'Braunschweig',
    'Bremen',
    'Bremerhaven',
    'Chemnitz',
    'Coburg',
    'Coesfeld',
    'Cottbus',
    'Darmstadt',
    'Deggendorf',
    'Dortmund',
    'Dresden',
    'Duisburg',
    'Dülmen',
    'Düren',
    'Düsseldorf',
    'Eschwege',
    'Essen',
    'Flensburg',
    'Frankfurt am Main',
    'Frankfurt/Oder',
    'Freiburg',
    'Friedberg',
    'Fritzlar',
    'Fulda',
    'Fürth',
    'Gelsenkirchen',
    'Gießen',
    'Gronau',
    'Göttingen',
    'Gütersloh',
    'Hagen',
    'Hamburg',
    'Hamm',
    'Hanau',
    'Hannover',
    'Hildesheim',
    'Hof',
    'Homburg',
    'Ingolstadt',
    'Iserlohn',
    'Jena',
    'Kaiserslautern',
    'Kassel',
    'Kempten (Allgäu)',
    'Kerpen',
    'Kiel',
    'Kleve',
    'Koblenz',
    'Korbach',
    'Krefeld',
    'Köln',
    'Königstein',
    'Landau',
    'Landshut',
    'Langenfeld',
    'Lebach',
    'Leipzig',
    'Lemgo',
    'Limburg',
    'Ludwigshafen a.Rhein (Ludwigshafen)',
    'Lübeck',
    'Lüdinghausen',
    'Lüneburg',
    'Mainz',
    'Mannheim',
    'Marburg',
    'Memmingen',
    'Merzig',
    'Montabaur',
    'Mönchengladbach',
    'München',
    'Münster',
    'Neubrandenburg',
    'Neunkirchen',
    'Neuruppin',
    'Neuss',
    'Nürnberg',
    'Offenbach am Main',
    'Oldenburg (Oldenburg)',
    'Osnabrück',
    'Ottweiler',
    'Paderborn',
    'Passau',
    'Pinneberg',
    'Potsdam',
    'Recklinghausen',
    'Regensburg',
    'Rostock',
    'Saarbrücken',
    'Saarlouis',
    'Schleiden',
    'Schweinfurt',
    'Schwerin',
    'Siegburg',
    'Siegen',
    'St. Ingbert (St Ingbert)',
    'St. Wendel (St Wendel)',
    'Stadthagen',
    'Steinfurt',
    'Stendal',
    'Stralsund',
    'Straubing',
    'Stuttgart',
    'Tostedt',
    'Traunstein',
    'Ulm',
    'Völklingen',
    'Walsrode',
    'Weiden i. d. OPf.',
    'Wetzlar',
    'Wiesbaden',
    'Wittlich',
    'Wuppertal',
    'Würzburg',
    'Zweibrücken',
]


RegisterType: TypeAlias = Literal['HRA', 'HRB', 'GnR', 'PR', 'VR', 'GsR', 'CH-HR']


class RelatedCompany(TypedDict):
    bilanz_type: NotRequired[str | None]
    display_name: str
    eu_id: NotRequired[str | None]
    legal_name: str
    object: NotRequired[Literal['related_company']]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    registered_seat: NotRequired[str | None]
    reporting_year: NotRequired[int | None]


class RelationshipsBlock(TypedDict):
    object: NotRequired[Literal['company_relationships']]
    parent_company: NotRequired[RelatedCompany | None]
    subsidiaries: NotRequired[list[RelatedCompany]]
    subsidiaries_total: NotRequired[int]


class SearchHit(TypedDict):
    address: NotRequired[Address | None]
    country_code: Literal['DE', 'CH']
    cpv_award_codes: NotRequired[list[str]]
    display_name: str
    employee_count: NotRequired[int | None]
    employee_count_year: NotRequired[int | None]
    eu_id: str
    financial_year: NotRequired[int | None]
    founded_at: NotRequired[str | None]
    is_branch: NotRequired[bool]
    legal_name: str
    legal_status: NotRequired[
        Literal['active', 'in_liquidation', 'insolvent', 'dissolved', 'deleted']
    ]
    object: NotRequired[Literal['search_hit']]
    profit: NotRequired[float | None]
    profit_year: NotRequired[int | None]
    register_canton: NotRequired[str | None]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    registered_seat: NotRequired[str | None]
    revenue: NotRequired[float | None]
    revenue_year: NotRequired[int | None]
    total_assets: NotRequired[float | None]
    total_assets_year: NotRequired[int | None]
    uid: NotRequired[str | None]
    website: NotRequired[str | None]


class SearchResponse(TypedDict):
    data: NotRequired[list[SearchHit]]
    execution_time_ms: NotRequired[int | None]
    filters_echo: NotRequired[dict[str, Any]]
    freshness: NotRequired[Freshness]
    object: NotRequired[Literal['list']]
    pagination: NotRequired[PaginationInfo]


class SeatEntry(TypedDict):
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    object: NotRequired[Literal['seat_entry']]
    seat: str


class Shareholder(TypedDict):
    display_name: str
    object: NotRequired[Literal['shareholder']]
    organization: NotRequired[OrganizationRef | None]
    party_type: Literal['natural_person', 'organization']
    person: NotRequired[Person | None]
    share_percent: NotRequired[float | None]
    shares_nominal: NotRequired[Money | None]
    total_shares: NotRequired[float | None]


class ShareholdersCoverage(TypedDict):
    object: NotRequired[Literal['shareholders_coverage']]
    status: NotRequired[
        Literal['available', 'not_applicable', 'not_filed', 'token_limit_reached']
    ]


class ShareholdersSnapshot(TypedDict):
    object: NotRequired[Literal['shareholders_snapshot']]
    shareholders: NotRequired[list[Shareholder]]


class SocialProfile(TypedDict):
    object: NotRequired[Literal['social_profile']]
    platform: str
    url: str


Sort: TypeAlias = Literal['name', 'revenue', 'profit', 'total_assets', 'employee_count']


SortDirection: TypeAlias = Literal['asc', 'desc']


class SubscriptionEvent(TypedDict):
    change_detected: bool
    delivery_attempted: bool
    delivery_attempts: int
    delivery_duration_ms: NotRequired[int | None]
    delivery_error: NotRequired[str | None]
    delivery_http_status: NotRequired[int | None]
    delivery_response_excerpt: NotRequired[str | None]
    event_id: str
    finished_at: NotRequired[str | None]
    notification_type: NotificationType | None
    object: NotRequired[Literal['subscription_event']]
    outcome: str
    publish_date_previous: NotRequired[str | None]
    publish_date_seen: NotRequired[str | None]
    request_body: NotRequired[dict[str, Any] | None]
    request_signature: NotRequired[str | None]
    request_timestamp: NotRequired[str | None]
    request_url: NotRequired[str | None]
    scrape_error_message: NotRequired[str | None]
    started_at: str


class SubscriptionEventList(TypedDict):
    data: NotRequired[list[SubscriptionEvent]]
    object: NotRequired[Literal['list']]
    pagination: NotRequired[PaginationInfo]


class SubscriptionEventResendResponse(TypedDict):
    duration_ms: int
    error: NotRequired[str | None]
    event: SubscriptionEvent
    http_status: NotRequired[int | None]
    object: NotRequired[Literal['subscription_event_resend']]
    succeeded: bool


class SubscriptionEventStatus(TypedDict):
    change_detected: bool
    delivery_attempted: bool
    delivery_attempts: int
    delivery_duration_ms: NotRequired[int | None]
    delivery_error: NotRequired[str | None]
    delivery_http_status: NotRequired[int | None]
    event_id: str
    finished_at: NotRequired[str | None]
    object: NotRequired[Literal['subscription_event_status']]
    outcome: str
    publish_date_previous: NotRequired[str | None]
    publish_date_seen: NotRequired[str | None]
    scrape_error_message: NotRequired[str | None]
    started_at: str


SubscriptionMode: TypeAlias = Literal['recurring', 'one_time']


SubscriptionType: TypeAlias = Literal[
    'details',
    'history',
    'shareholders',
    'ubo',
    'doc_articles_of_association',
    'doc_company_registration',
    'doc_model_protocol',
    'doc_shareholder_list',
]


TenderRole: TypeAlias = Literal['winner', 'buyer']


class UboCoverage(TypedDict):
    object: NotRequired[Literal['ubo_coverage']]
    reason: NotRequired[str | None]
    status: NotRequired[Literal['available', 'partial', 'not_applicable', 'not_filed']]


class UboEdge(TypedDict):
    object: NotRequired[Literal['ubo_edge']]
    share_percent: NotRequired[float | None]
    source_id: str
    target_id: str


class UboNode(TypedDict):
    eu_id: NotRequired[str | None]
    id: str
    is_root: NotRequired[bool]
    is_unresolved: NotRequired[bool]
    node_type: Literal['company', 'person', 'organization_unresolved']
    object: NotRequired[Literal['ubo_node']]
    organization: NotRequired[OrganizationRef | None]
    person: NotRequired[Person | None]
    unresolved_reason: NotRequired[
        Literal[
            'foreign_org', 'unlisted_org', 'cap_table_not_filed', 'max_depth_reached'
        ]
        | None
    ]


class WebhookTestAttempt(TypedDict):
    attempt: int
    duration_ms: int
    error: NotRequired[str | None]
    http_status: NotRequired[int | None]
    object: NotRequired[Literal['webhook_test_attempt']]
    response_excerpt: NotRequired[str | None]
    sent_signature_header: str
    sent_timestamp_header: str
    succeeded: bool


WebhookTestDeliveryScenario: TypeAlias = Literal[
    'success', 'retry_delivery', 'bad_signature', 'stale_timestamp'
]


class WebsiteEntry(TypedDict):
    domain: str
    impressum_url: NotRequired[str | None]
    is_primary: NotRequired[bool]
    object: NotRequired[Literal['company_website']]
    verification: NotRequired[str]


class Wz2025Score(TypedDict):
    code: str
    description: NotRequired[str | None]
    object: NotRequired[Literal['wz_2025_score']]
    score: NotRequired[float | None]
    section: NotRequired[str | None]


class AiInsightsBlock(TypedDict):
    based_on_fiscal_year: NotRequired[int | None]
    generated_at: NotRequired[str | None]
    object: NotRequired[Literal['ai_insights']]
    outlook: NotRequired[LocalizedText | None]
    summary: NotRequired[LocalizedText | None]


class AutocompleteResponse(TypedDict):
    data: NotRequired[list[AutocompleteHit]]
    filters_echo: NotRequired[dict[str, Any]]
    freshness: NotRequired[Freshness]
    object: NotRequired[Literal['list']]
    pagination: NotRequired[PaginationInfo]


class BeneficialOwner(TypedDict):
    effective_share_percent: float
    node_id: str
    object: NotRequired[Literal['beneficial_owner']]
    person: Person


class BoardChange(TypedDict):
    change: Literal['appointed', 'departed', 'updated']
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    object: NotRequired[Literal['board_change']]
    organization: NotRequired[OrganizationRef | None]
    person: NotRequired[Person | None]
    representation: NotRequired[BoardRepresentation | None]
    role: NotRequired[str | None]


class BoardMember(TypedDict):
    appointed_date: NotRequired[str | None]
    object: NotRequired[Literal['board_member']]
    organization: NotRequired[OrganizationRef | None]
    person: NotRequired[Person | None]
    representation: NotRequired[BoardRepresentation | None]
    role: NotRequired[str | None]


class BranchEntry(TypedDict):
    branches: NotRequired[list[HistoryBranch]]
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    object: NotRequired[Literal['branch_entry']]


class BusinessBlock(TypedDict):
    business_branches: NotRequired[list[BusinessBranch]]
    object: NotRequired[Literal['company_business']]
    opportunity_keywords: NotRequired[list[str]]
    products: NotRequired[list[str]]
    risk_keywords: NotRequired[list[str]]


class CapitalEntry(TypedDict):
    amount: Money
    change: NotRequired[Money | None]
    change_type: Literal[
        'initial',
        'cash_increase',
        'contribution_in_kind',
        'from_authorized_capital',
        'from_conditional_capital',
        'decrease',
        'unchanged',
    ]
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    object: NotRequired[Literal['capital_entry']]


class CompanyDocumentDownload(TypedDict):
    document_id: NotRequired[str | None]
    download_url: str
    download_url_expires_at: str
    file_id: str
    file_name_de: str
    file_name_en: str
    freshness: Freshness
    is_outdated: NotRequired[bool]
    label: NotRequired[str | None]
    object: NotRequired[Literal['company_document_download']]
    published_at: NotRequired[str | None]
    type: Literal[
        'register_extract_current',
        'register_extract_chronological',
        'shareholder_list',
        'articles_of_association',
        'company_registration',
        'model_protocol',
    ]
    type_label_de: str
    type_label_en: str
    updated_at: str


class CompanyDocumentList(TypedDict):
    country_code: Literal['DE', 'CH']
    coverage: DocumentsCoverage
    data: list[CompanyDocumentListItem]
    eu_id: str
    freshness: Freshness
    object: NotRequired[Literal['company_document_list']]


class CompanyListDetailResponse(TypedDict):
    data: NotRequired[list[SearchHit]]
    filters_echo: NotRequired[dict[str, Any]]
    list_id: int
    name: str
    object: NotRequired[Literal['list']]
    pagination: NotRequired[PaginationInfo]


class CompanyListsResponse(TypedDict):
    data: NotRequired[list[CompanyListSummary]]
    filters_echo: NotRequired[dict[str, Any]]
    object: NotRequired[Literal['list']]
    pagination: NotRequired[PaginationInfo]


class ContactBlock(TypedDict):
    impressum_url: NotRequired[str | None]
    object: NotRequired[Literal['company_contact']]
    social_profiles: NotRequired[list[SocialProfile]]
    website: NotRequired[str | None]
    websites: NotRequired[list[WebsiteEntry]]


class EmployeeHistoryBlock(TypedDict):
    object: NotRequired[Literal['employee_history']]
    series: NotRequired[list[EmployeeYear]]


class FinancialMetric(TypedDict):
    balance_sheet_total: NotRequired[Money | None]
    ceiling_basis: NotRequired[str | None]
    gross_profit: NotRequired[Money | None]
    liabilities_and_equity_total: NotRequired[Money | None]
    object: NotRequired[Literal['financial_metric']]
    other_operating_income: NotRequired[Money | None]
    profit: NotRequired[Money | None]
    revenue: NotRequired[Money | None]
    revenue_ceiling: NotRequired[Money | None]
    size_basis: NotRequired[str | None]
    size_class: NotRequired[str | None]
    year: int


class FinancialSummaryBlock(TypedDict):
    latest_employee_count: NotRequired[int | None]
    latest_employee_count_year: NotRequired[int | None]
    latest_fiscal_year: NotRequired[int | None]
    latest_profit: NotRequired[Money | None]
    latest_profit_year: NotRequired[int | None]
    latest_revenue: NotRequired[Money | None]
    latest_revenue_year: NotRequired[int | None]
    latest_total_assets: NotRequired[Money | None]
    latest_total_liabilities_and_equity: NotRequired[Money | None]
    object: NotRequired[Literal['financial_summary']]


class FounderProfileBlock(TypedDict):
    as_of: NotRequired[str | None]
    evidence_source: NotRequired[str | None]
    family_confidence: NotRequired[Literal['confirmed', 'likely'] | None]
    family_managed: NotRequired[bool | None]
    family_signals: NotRequired[list[str]]
    family_surname: NotRequired[str | None]
    founder_count: NotRequired[int]
    founder_led: NotRequired[bool | None]
    founder_led_confidence: NotRequired[Literal['confirmed', 'likely'] | None]
    founder_led_since: NotRequired[str | None]
    founders: NotRequired[list[FounderRecordItem]]
    object: NotRequired[Literal['founder_profile']]
    oldest_founder_birth_year: NotRequired[int | None]
    succession_risk: NotRequired[bool | None]


class IndustryBlock(TypedDict):
    object: NotRequired[Literal['company_industry']]
    primary_wz_2025_code: NotRequired[str | None]
    wz_2025_codes: NotRequired[list[Wz2025Score]]


class LeiGraphBlock(TypedDict):
    direct_children: NotRequired[list[LeiRelative]]
    direct_children_total: NotRequired[int]
    direct_parent: NotRequired[LeiRelative | None]
    lei_code: NotRequired[str | None]
    object: NotRequired[Literal['lei_graph']]


class LimitedPartner(TypedDict):
    contribution: NotRequired[Money | None]
    entry_date: NotRequired[str | None]
    entry_number: NotRequired[int | None]
    object: NotRequired[Literal['limited_partner']]
    organization: NotRequired[OrganizationRef | None]
    person: NotRequired[Person | None]
    share_percent: NotRequired[float | None]


class Member(TypedDict):
    object: NotRequired[Literal['member']]
    organization: NotRequired[OrganizationRef | None]
    person: NotRequired[Person | None]
    role: NotRequired[str | None]
    role_code: NotRequired[str | None]


class ShareholdersReport(TypedDict):
    as_of_snapshot: NotRequired[ShareholdersSnapshot | None]
    coverage: ShareholdersCoverage
    eu_id: str
    freshness: Freshness
    object: NotRequired[Literal['shareholders_report']]


class Subscription(TypedDict):
    cadence: NotificationCadence | None
    cadence_seconds: int
    created_at: str
    eu_id: str
    id: str
    language: NotRequired[NotificationLanguage]
    last_attempted_at: NotRequired[str | None]
    last_event: NotRequired[SubscriptionEventStatus | None]
    latest_succeeded_publish_date: NotRequired[str | None]
    mode: SubscriptionMode
    notification_type: NotificationType | None
    object: NotRequired[Literal['subscription']]
    recipient_email: NotRequired[str | None]
    subscription_end_date: NotRequired[str | None]
    subscription_type: SubscriptionType
    updated_at: str
    webhook_url: NotRequired[str | None]


class SubscriptionCreateRequest(TypedDict):
    cadence: NotRequired[NotificationCadence]
    eu_id: str
    language: NotRequired[NotificationLanguage]
    mode: NotRequired[SubscriptionMode]
    notification_type: NotRequired[NotificationType | None]
    recipient_email: NotRequired[str | None]
    subscription_end_date: NotRequired[str | None]
    subscription_type: SubscriptionType
    webhook_url: NotRequired[str | None]


class SubscriptionCreated(TypedDict):
    cadence: NotificationCadence | None
    cadence_seconds: int
    created_at: str
    eu_id: str
    id: str
    language: NotRequired[NotificationLanguage]
    last_attempted_at: NotRequired[str | None]
    last_event: NotRequired[SubscriptionEventStatus | None]
    latest_succeeded_publish_date: NotRequired[str | None]
    mode: SubscriptionMode
    notification_type: NotificationType | None
    object: NotRequired[Literal['subscription_created']]
    recipient_email: NotRequired[str | None]
    subscription_end_date: NotRequired[str | None]
    subscription_type: SubscriptionType
    updated_at: str
    webhook_secret: NotRequired[str | None]
    webhook_url: NotRequired[str | None]


class SubscriptionList(TypedDict):
    data: NotRequired[list[Subscription]]
    object: NotRequired[Literal['list']]
    pagination: NotRequired[PaginationInfo]


class SubscriptionTestRequest(TypedDict):
    delivery_scenario: NotRequired[WebhookTestDeliveryScenario]
    eu_id: str
    language: NotRequired[NotificationLanguage]
    notification_type: NotificationType
    recipient_email: NotRequired[str | None]
    scenario: NotRequired[Literal['change']]
    subscription_type: SubscriptionType
    webhook_url: NotRequired[str | None]


class SubscriptionTestResponse(TypedDict):
    attempts: NotRequired[list[WebhookTestAttempt] | None]
    delivery_scenario: NotRequired[WebhookTestDeliveryScenario | None]
    duration_ms: int
    notification_type: NotificationType
    object: NotRequired[Literal['subscription_test_result']]
    receiver_error: NotRequired[str | None]
    receiver_http_status: NotRequired[int | None]
    receiver_response_excerpt: NotRequired[str | None]
    receiver_succeeded: bool
    recipient_email: NotRequired[str | None]
    sent_body: NotRequired[dict[str, Any] | None]
    sent_body_html: NotRequired[str | None]
    sent_event_id: NotRequired[str | None]
    sent_event_type: NotRequired[str | None]
    sent_signature_header: NotRequired[str | None]
    sent_subject: NotRequired[str | None]
    sent_timestamp_header: NotRequired[str | None]
    webhook_secret: NotRequired[str | None]
    webhook_url: NotRequired[str | None]


class UboGraph(TypedDict):
    edges: NotRequired[list[UboEdge]]
    nodes: NotRequired[list[UboNode]]
    object: NotRequired[Literal['ubo_graph']]
    root_id: str


class UboReport(TypedDict):
    beneficial_owners: NotRequired[list[BeneficialOwner]]
    coverage: UboCoverage
    eu_id: str
    freshness: Freshness
    graph: UboGraph
    has_unresolved_branches: NotRequired[bool]
    object: NotRequired[Literal['ubo_report']]
    potential_beneficial_owners: NotRequired[list[PotentialBeneficialOwner]]


class CompanyDetail(TypedDict):
    address: NotRequired[Address | None]
    ai_insights: NotRequired[AiInsightsBlock | None]
    business_info: NotRequired[BusinessBlock | None]
    business_purpose: NotRequired[str | None]
    contact: ContactBlock
    country_code: Literal['DE', 'CH']
    display_name: str
    documents: NotRequired[list[CompanyDocument]]
    elf_code: NotRequired[str | None]
    eu_id: str
    financial_summary: NotRequired[FinancialSummaryBlock | None]
    first_register_entry_at: NotRequired[str | None]
    founder_profile: NotRequired[FounderProfileBlock | None]
    founding_document_date: NotRequired[str | None]
    freshness: Freshness
    industry_categorization: IndustryBlock
    insolvency: NotRequired[InsolvencyBlock | None]
    is_branch: NotRequired[bool]
    latest_register_entry_date: NotRequired[str | None]
    legal_form: NotRequired[str | None]
    legal_name: NotRequired[str | None]
    legal_status: NotRequired[
        Literal['active', 'in_liquidation', 'insolvent', 'dissolved', 'deleted']
    ]
    lei_graph: NotRequired[LeiGraphBlock | None]
    management: NotRequired[list[Member]]
    object: NotRequired[Literal['company']]
    register_canton: NotRequired[str | None]
    register_court: NotRequired[str | None]
    register_number: NotRequired[int | None]
    register_type: NotRequired[str | None]
    registered_seat: NotRequired[str | None]
    share_capital: NotRequired[Money | None]
    uid: NotRequired[str | None]
    ust_id_nr: NotRequired[str | None]
    wirtschafts_id_nr: NotRequired[str | None]


class CompanyHistory(TypedDict):
    articles_of_association: NotRequired[list[ArticlesEntry]]
    board_changes: NotRequired[list[BoardChange]]
    branches: NotRequired[list[BranchEntry]]
    business_addresses: NotRequired[list[AddressEntry]]
    business_purposes: NotRequired[list[PurposeEntry]]
    coverage: HistoryCoverage
    current_board: NotRequired[list[BoardMember]]
    eu_id: str
    first_entry: NotRequired[FirstRegisterEntry | None]
    freshness: Freshness
    legal_forms: NotRequired[list[LegalFormEntry]]
    legal_status: NotRequired[str | None]
    legal_status_events: NotRequired[list[LegalStatusEvent]]
    limited_partners: NotRequired[list[LimitedPartner]]
    names: NotRequired[list[NameEntry]]
    object: NotRequired[Literal['company_history']]
    seats: NotRequired[list[SeatEntry]]
    share_capital: NotRequired[list[CapitalEntry]]


class FinancialHistoryBlock(TypedDict):
    assets: NotRequired[list[FinancialRow]]
    liabilities_and_equity: NotRequired[list[FinancialRow]]
    metrics: NotRequired[list[FinancialMetric]]
    object: NotRequired[Literal['financial_history']]
    profit_and_loss: NotRequired[list[FinancialRow]]


class CompanyFinancials(TypedDict):
    employee_history: EmployeeHistoryBlock
    eu_id: str
    financial_publications: NotRequired[list[FinancialPublication]]
    freshness: Freshness
    history: FinancialHistoryBlock
    object: NotRequired[Literal['company_financials']]
    relationships: NotRequired[RelationshipsBlock | None]
    summary: NotRequired[FinancialSummaryBlock | None]
