"""Regenerate the typed surface from ``contracts/openapi.v1.json``.

    python scripts/generate_types.py

Writes two files, both committed:

* ``src/firmendata/types.py``  — response bodies, via datamodel-code-generator.
* ``src/firmendata/params.py`` — query-parameter TypedDicts, generated here.

The second exists because datamodel-code-generator models *schemas*, and
query parameters are not schemas. ``/v1/companies/search`` alone takes 36 of
them; hand-writing that signature in two clients would be ~70 lines of noise
that silently rots the first time the API grows a filter. Instead the clients
take ``**filters: Unpack[SearchFilters]``, so editors still complete every
field and the list is regenerated rather than remembered.

CI runs this and fails if the output differs from what is committed, which is
what keeps the SDK honest about the contract it vendors.
"""

from __future__ import annotations

import json
import keyword
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
SPEC = REPO / "contracts" / "openapi.v1.json"
TYPES_OUT = REPO / "src" / "firmendata" / "types.py"
PARAMS_OUT = REPO / "src" / "firmendata" / "params.py"

# Operations whose query parameters get a generated TypedDict, and the name
# to give it. Path parameters are explicit arguments on the client methods,
# so they are excluded below.
PARAM_MODELS: dict[tuple[str, str], str] = {
    ("/v1/companies/search", "get"): "SearchFilters",
    ("/v1/subscriptions", "get"): "SubscriptionFilters",
}


def _resolve(schema: dict[str, Any], root: dict[str, Any]) -> dict[str, Any]:
    while "$ref" in schema:
        node: Any = root
        for part in schema["$ref"].lstrip("#/").split("/"):
            node = node[part]
        schema = node
    return schema


def _py_type(schema: dict[str, Any], root: dict[str, Any]) -> str:
    """Best-effort OpenAPI schema → Python annotation."""
    schema = _resolve(schema, root)

    if "anyOf" in schema:
        options = [o for o in schema["anyOf"] if _resolve(o, root).get("type") != "null"]
        if not options:
            return "Any"
        # Nullability is implicit: every generated field is NotRequired, and
        # omitting a filter is how you say "don't filter", so `| None` would
        # only add noise at the call site.
        return " | ".join(dict.fromkeys(_py_type(o, root) for o in options))

    if "enum" in schema:
        literals = ", ".join(repr(v) for v in schema["enum"])
        return f"Literal[{literals}]"

    kind = schema.get("type")
    if kind == "array":
        return f"list[{_py_type(schema.get('items', {}), root)}]"
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
    }.get(kind, "Any")


def build_params_module(spec: dict[str, Any]) -> str:
    lines = [
        '"""Query-parameter types. Generated by scripts/generate_types.py."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal, NotRequired, TypedDict",
        "",
        "__all__ = [" + ", ".join(repr(n) for n in PARAM_MODELS.values()) + "]",
        "",
    ]

    for (path, method), name in PARAM_MODELS.items():
        operation = spec["paths"][path][method]
        lines += ["", f"class {name}(TypedDict, total=False):"]
        summary = operation.get("summary", "").strip()
        lines.append(f'    """{summary or name}."""')
        lines.append("")

        wrote_any = False
        for param in operation.get("parameters", []):
            if param.get("in") != "query":
                continue
            field = param["name"]
            if keyword.iskeyword(field):  # pragma: no cover - none today
                raise SystemExit(f"parameter {field!r} collides with a Python keyword")
            annotation = _py_type(param.get("schema", {}), spec)
            description = " ".join((param.get("description") or "").split())
            if description:
                if len(description) > 88:
                    description = description[:85].rstrip() + "..."
                lines.append(f"    # {description}")
            lines.append(f"    {field}: NotRequired[{annotation}]")
            wrote_any = True
        if not wrote_any:  # pragma: no cover - defensive
            lines.append("    pass")

    return "\n".join(lines) + "\n"


def main() -> int:
    if not SPEC.exists():
        print(f"missing {SPEC}", file=sys.stderr)
        return 1
    spec = json.loads(SPEC.read_text(encoding="utf-8"))

    print("generating response types…")
    result = subprocess.run(
        [
            sys.executable, "-m", "datamodel_code_generator",
            "--input", str(SPEC),
            "--input-file-type", "openapi",
            "--output-model-type", "typing.TypedDict",
            "--target-python-version", "3.11",
            "--use-standard-collections",
            "--use-union-operator",
            # Without this the header carries a generation timestamp, so the
            # output differs on every run and the CI drift check can never
            # pass — it would only ever report the clock moving.
            "--disable-timestamp",
            "--formatters", "black",
            "--output", str(TYPES_OUT),
        ],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        print(
            "\ndatamodel-code-generator failed. Install it with "
            "`pip install 'datamodel-code-generator[http]'`.",
            file=sys.stderr,
        )
        return result.returncode

    print("generating query-parameter types…")
    PARAMS_OUT.write_text(build_params_module(spec), encoding="utf-8")

    print(f"wrote {TYPES_OUT.relative_to(REPO)} and {PARAMS_OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
